### PR TITLE
Adopt case_utils, and import namespace prefixes

### PR DESCRIPTION
**Pull request by ajnelson-nist**

### CODE REVIEW

**Comment by ajnelson-nist** [comment]
I'm uncertain if this will fail CI.  I suggest by the time this PR is merged, it pass CI.

**Comment by red-ship-it** [comment]
This seems to be ready to merge, 
- Bnodes have been removed
-  The prefixes for UUIDS are a little less than clean I'm going to add some extra thought into this part.
- There also seems to be a kb: pre the prefixes im not sure if this is an example or if it's a rationale that is required, will have a look

**Comment by ajnelson-nist** [comment]
> * The prefixes for UUIDS are a little less than clean I'm going to add some extra thought into this part.

RDFLib's `Namespace` object has a dictionary-access operator that generates `URIRef`s when you look up a strong.

So, given this snippet of setup:

```python
import uuid
from rdflib import Namespace

ns_kb = Namespace("http://example.org/kb/")
```

This would create a `URIRef`:

```python
ns_kb["thing-" + str(uuid.uuid4())]
```

You're already using the `case_utils.local_uuid.local_uuid()` method, so you don't need to import the `uuid` base Python module.  However, you should be aware that if you want that to generate UUID5s consistently for the sake of example data in this repo, that function's calling environment needs to be set up with [two environment assumptions](https://github.com/casework/CASE-Utilities-Python/blob/0.9.0/case_utils/local_uuid.py#L110-L115): A certain environment variable being set; and `case_utils.local_uuid.configure()` being called.  ...And, I now realize, the `configure()` part isn't documented in that function.  I'll fix that.

**Comment by ajnelson-nist** [comment]
I have a suggestion for one of the helper functions.

`get_uuid_stub` is currently ([cb351e2](https://github.com/casework/CASE-Implementation-PyPI-Exifread/pull/9/commits/cb351e207677c88abcde9148aaae8a4dccdb3392)) spelled like this:

```python
def get_uuid_stub(ns):
    uuid = f"kb:{ns}-{case_utils.local_uuid.local_uuid()}"
    return uuid
```

The purpose is to take in some portion of a prefix, and return an IRI for annotating (placing as a member of triples) in the graph, e.g. `URIRef("http://example.org/kb/thing-bce14124-1d3d-4c22-8a66-8ba3e85af558")`.  The compacted JSON-LD spelling for that IRI would be `kb:thing-bce14124-1d3d-4c22-8a66-8ba3e85af558`.

So, the return type should be a `URIRef`.  And then, the input to the function should configure the namespace to use, as well as a "slug".  I'd say "prefix" instead of "slug", but then we're overloading.  I'm referring specifically to the portion of the returned string that is `"thing-"`.

If you give an extra argument for the slug, and assign types for the ins & outs, you'll see the name should also be adjusted because it isn't quite getting the purpose of the "uuid" bit right.  I suggest the signature become:

```python
def get_node_iri(ns: rdflib.Namespace, slug: str) -> rdflib.URIRef:
```

(This also helps avoid an accidental variable collision.  `uuid` is the name of a commonly-imported Python base package also named `uuid`.)

**Comment by red-ship-it** [comment]
I shall add these points you have suggested, thanks.

**Pull request merged**
